name: SmartContract

on:
  push:
    branches:
      - main
      - releases/*

jobs:
  install_dependencies:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]  
        node-version: [16.x]    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
          cache: npm
      - run: |
          npm install --save-dev hardhat

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]  
        node-version: [16.x]  
    steps:
      - uses: actions/checkout@v3
      - name: Unit Test 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
          cache: npm
      - run: npx hardhat test       

  deploy:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]  
        node-version: [16.x]  
    steps:
      - uses: actions/checkout@v3
      - name: build contract
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
          cache: npm
      - run:  npx hardhat run scripts/deploy.js --network kovan        

         
